apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devops-platform
  labels:
    app: backend
data:
  NODE_ENV: production
  PORT: "8080"
  MONGODB_DATABASE: devops_platform
