apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: devops-platform
  labels:
    app: backend
type: Opaque
stringData:
  MONGODB_URI: mongodb://devops:devops-password@mongodb:27017/devops_platform?authSource=admin
