apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: devops-platform
  labels:
    app: backend
type: Opaque
stringData:
  MONGODB_URI: mongodb://devops:devops-password@mongodb-0.mongodb-headless:27017,mongodb-1.mongodb-headless:27017,mongodb-2.mongodb-headless:27017/devops_platform?authSource=admin&replicaSet=rs0
