apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../backend
  - ../../frontend
  - ../../mongodb
  - ../../monitoring
  - ../../ingress

images:
  - name: ghcr.io/zhongminma/devops-platform-backend
    newName: devops-platform-backend
    newTag: local
