output "cluster_full_name" {
  description = "Full cluster name generated by the EKS module."
  value       = local.cluster_full_name
}

output "cluster_name" {
  description = "Name of the EKS cluster."
  value       = aws_eks_cluster.this.name
}

output "cluster_arn" {
  description = "ARN of the EKS cluster."
  value       = aws_eks_cluster.this.arn
}

output "cluster_endpoint" {
  description = "Endpoint URL for the EKS Kubernetes API server."
  value       = aws_eks_cluster.this.endpoint
}

output "cluster_certificate_authority_data" {
  description = "Base64 encoded certificate data required to communicate with the cluster."
  value       = aws_eks_cluster.this.certificate_authority[0].data
  sensitive   = true
}

output "cluster_role_arn" {
  description = "ARN of the IAM role used by the EKS control plane."
  value       = aws_iam_role.cluster.arn
}

output "node_group_role_arn" {
  description = "ARN of the IAM role used by EKS managed node groups."
  value       = aws_iam_role.node_group.arn
}

output "kubernetes_version" {
  description = "Kubernetes version configured for the EKS control plane."
  value       = aws_eks_cluster.this.version
}

output "private_subnet_ids" {
  description = "Private subnet IDs passed to the EKS module."
  value       = var.private_subnet_ids
}

output "endpoint_private_access" {
  description = "Whether private EKS endpoint access is enabled."
  value       = var.endpoint_private_access
}

output "endpoint_public_access" {
  description = "Whether public EKS endpoint access is enabled."
  value       = var.endpoint_public_access
}

output "node_group_name" {
  description = "Name of the default EKS managed node group."
  value       = aws_eks_node_group.default.node_group_name
}

output "node_group_arn" {
  description = "ARN of the default EKS managed node group."
  value       = aws_eks_node_group.default.arn
}

output "cluster_addons" {
  description = "EKS add-ons configured for the cluster."
  value       = sort(keys(aws_eks_addon.this))
}
