output "cluster_full_name" {
  description = "Full cluster name generated by the EKS module."
  value       = local.cluster_full_name
}

output "kubernetes_version" {
  description = "Kubernetes version configured for the EKS control plane."
  value       = var.kubernetes_version
}

output "private_subnet_ids" {
  description = "Private subnet IDs passed to the EKS module."
  value       = var.private_subnet_ids
}

output "endpoint_private_access" {
  description = "Whether private EKS endpoint access is enabled."
  value       = var.endpoint_private_access
}

output "endpoint_public_access" {
  description = "Whether public EKS endpoint access is enabled."
  value       = var.endpoint_public_access
}
