apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: devops-platform
  labels:
    app: mongodb
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: 27017
      targetPort: 27017
