apiVersion: v1
kind: Secret
metadata:
  name: mongodb-keyfile
  namespace: devops-platform
  labels:
    app: mongodb
type: Opaque
stringData:
  keyfile: devops-platform-local-mongodb-replica-set-key-please-rotate
