apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.yaml
  - keyfile-secret.yaml
  - service.yaml
  - headless-service.yaml
  - statefulset.yaml
  - init-replica-set-job.yaml
