apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-platform
  namespace: argocd
  labels:
    app.kubernetes.io/name: devops-platform
spec:
  project: default
  source:
    repoURL: https://github.com/zhongminma/devops-platform-k8s.git
    targetRevision: main
    path: k8s/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
