output "project_name" {
  description = "Project name used for resources."
  value       = var.project_name
}

output "environment" {
  description = "Environment name."
  value       = var.environment
}

output "aws_region" {
  description = "AWS region for this environment."
  value       = var.aws_region
}

output "cluster_name" {
  description = "Planned EKS cluster name."
  value       = var.cluster_name
}

output "network_name_prefix" {
  description = "Name prefix generated by the network module."
  value       = module.network.name_prefix
}

output "network_vpc_cidr" {
  description = "VPC CIDR passed to the network module."
  value       = module.network.vpc_cidr
}

output "eks_cluster_full_name" {
  description = "Full cluster name generated by the EKS module."
  value       = module.eks.cluster_full_name
}

output "eks_kubernetes_version" {
  description = "Kubernetes version configured by the EKS module."
  value       = module.eks.kubernetes_version
}

output "network_vpc_id" {
  description = "VPC ID created by the network module."
  value       = module.network.vpc_id
}

output "network_internet_gateway_id" {
  description = "Internet gateway ID created by the network module."
  value       = module.network.internet_gateway_id
}

output "network_public_route_table_id" {
  description = "Public route table ID created by the network module."
  value       = module.network.public_route_table_id
}

output "network_private_route_table_id" {
  description = "Private route table ID created by the network module."
  value       = module.network.private_route_table_id
}

output "network_nat_gateway_id" {
  description = "NAT gateway ID created by the network module, if enabled."
  value       = module.network.nat_gateway_id
}

output "network_nat_eip_public_ip" {
  description = "NAT gateway EIP public IP, if enabled."
  value       = module.network.nat_eip_public_ip
}

output "network_public_subnet_ids" {
  description = "Public subnet IDs created by the network module."
  value       = module.network.public_subnet_ids
}

output "network_private_subnet_ids" {
  description = "Private subnet IDs created by the network module."
  value       = module.network.private_subnet_ids
}

output "eks_cluster_role_arn" {
  description = "IAM role ARN used by the EKS control plane."
  value       = module.eks.cluster_role_arn
}

output "eks_node_group_role_arn" {
  description = "IAM role ARN used by EKS managed node groups."
  value       = module.eks.node_group_role_arn
}

output "eks_cluster_arn" {
  description = "ARN of the EKS cluster."
  value       = module.eks.cluster_arn
}

output "eks_cluster_endpoint" {
  description = "Endpoint URL for the EKS Kubernetes API server."
  value       = module.eks.cluster_endpoint
}

output "eks_node_group_name" {
  description = "Name of the default EKS managed node group."
  value       = module.eks.node_group_name
}

output "eks_node_group_arn" {
  description = "ARN of the default EKS managed node group."
  value       = module.eks.node_group_arn
}
